export enum AnswerType {
  INPUT = 'INPUT',
  TEXT_AREA = 'TEXT_AREA',
  MULTIPLE_SELECTION = 'MULTIPLE_SELECTION',
  SINGLE_SELECTION_LIST = 'SINGLE_SELECTION_LIST',
  SINGLE_SELECTION_RADIO = 'SINGLE_SELECTION_RADIO'
}
