export enum VariableFormat {
  TEXT = 'TEXT',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  NUMBER = 'NUMBER',
  FLOAT = 'FLOAT',
  POSITIVE_NUMBER = 'POSITIVE_NUMBER',
  NEGATIVE_NUMBER = 'NEGATIVE_NUMBER',
  POSITIVE_FLOAT = 'POSITIVE_FLOAT',
  NEGATIVE_FLOAT = 'NEGATIVE_FLOAT',
  DATE = 'DATE',
  POSTAL_CODE = 'POSTAL_CODE',
  DATE_PAST = 'DATE_PAST',
  DATE_FUTURE = 'DATE_FUTURE',
  BSN = 'BSN',
  IBAN = 'IBAN'
}
